"""Create PenjualanBatik table

Revision ID: c31397c4fcda
Revises: 
Create Date: 2024-11-05 20:05:36.522582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c31397c4fcda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penjualan_batik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waktu_transaksi', sa.String(length=50), nullable=True),
    sa.Column('nama_produk', sa.String(length=255), nullable=True),
    sa.Column('kategori_produk', sa.String(length=50), nullable=True),
    sa.Column('jumlah_produk_dipesan', sa.Integer(), nullable=True),
    sa.Column('total_pembayaran', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.drop_table('penjualan_batik')
    # ### end Alembic commands ###
